import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers'
import { CssBaseline } from '@mui/material'
import NextProviders from '@/components/NextProviders'
import { MuiThemeProvider } from '@/themes/MuiThemeProvider'
import { ReactNode } from 'react'
import ProgressBar from '@/components/layout/ProgressBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    const cookieStores = cookies()
    const theme = cookieStores.get('theme')
    return (
        <html
            lang="en"
            data-theme={theme?.value}
            suppressHydrationWarning>
            <body className={inter.className}>
                <NextProviders>
                    <MuiThemeProvider initialTheme={theme?.value as 'light' | 'dark'}>
                        <CssBaseline />
                        <ProgressBar />
                        {children}
                    </MuiThemeProvider>
                </NextProviders>
            </body>
        </html>
    )
}
